### ISSUE TITLE
Police/amublance/taxi dont work when you click it

### ISSUE THREAD

**Issue by ExoticNx** [FXServer-ESX/fxserver-esx_phone#10]
title says it

**Comment by vegnagun** [comment]
hello i have fixed that you want my version ?

**Comment by funzik** [comment]
i have the same problem, call to police, ambulance etc... don't work

**Comment by RomainLanz** [comment]
Hey 👋 

Have you updated the related service code?
This script got a huge update latelly that needs to be reflected on your code.

**Comment by ExoticNx** [comment]
Rep my friend gave me his and it's working a ok thanks

**Comment by RomainLanz** [comment]
Cool!

I'm closing this one.
Feel free to open another issue if you still got troubles.
