### ISSUE TITLE
Unable to add a contact

### ISSUE THREAD

**Issue by edgegamers** [FXServer-ESX/fxserver-esx_phone#2]
[    147234] Error running call reference function for resource esx_phone: server/main.lua:203: attempt to index a nil value (local 'xPlayer')
[    147234] stack traceback:
[    147234] 	server/main.lua:203: in local 'ref'
[    147234] 	citizen:/scripting/lua/scheduler.lua:277: in function <citizen:/scripting/lua/scheduler.lua:268>
[    147234] [ERROR] [] Check the error above, an error happens when executing the callback from the query : "SELECT phone_number FROM users WHERE phone_number = @number {@number=82784}"

**Comment by indilo53** [comment]
Try it now and tell me if it works

**Comment by edgegamers** [comment]
Looks like it was added, but its not showing up in the phone
http://i.imgur.com/SB7xpU9.jpg

**Comment by edgegamers** [comment]
Texting a taxi works

**Comment by indilo53** [comment]
It should work now, please restart your server, remove the contact and try to add him again

**Comment by edgegamers** [comment]
Ok it is working - http://i.imgur.com/BzbSRXz.jpg - Though the other user sent a request to be added to his, but I never received the request. He's in my contact list, but I am not in his.

**Comment by indilo53** [comment]
He have to add you as a contact

**Comment by edgegamers** [comment]
So we are able to message each other, but when he goes into contacts, I am not there. He has the option to add, but it says I am already in his contact list

**Comment by indilo53** [comment]
In the database, the contact is added ? Does he restarted the client ?

**Comment by edgegamers** [comment]
http://i.imgur.com/QqQXJAY.png

**Comment by edgegamers** [comment]
Should the users have to restart their client if adding a new contact?

**Comment by indilo53** [comment]
So it is added. Let him restart the client to check if he can see you as contact. If yes, he try to delete and re-add you as a contact.

**Comment by indilo53** [comment]
No they sould not restart the client but it is for testing

**Comment by edgegamers** [comment]
I just saw another update on this repo, just ran git pull one sec let me test.

**Comment by edgegamers** [comment]
That did it. It is working just fine now... Thank you !!!

**Comment by indilo53** [comment]
Cool :)

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
