### ISSUE TITLE
Police and ambulance is missing

### ISSUE THREAD

**Issue by UtraTM** [FXServer-ESX/fxserver-esx_phone#3]
Hello,

the police and ambulance is missing to be able to call them.

Thx for the nice work

**Comment by indilo53** [comment]
Fixed 

https://github.com/FXServer-ESX/fxserver-esx_phone/commit/7acfc3e4fbb2db931d493c15c86c57b89da599fd
https://github.com/FXServer-ESX/fxserver-esx_ambulancejob/commit/d39bb1e4d516049f628a9794e4c8283b36a80a37
https://github.com/FXServer-ESX/fxserver-esx_policejob/commit/37e5ad4afa9a886a5584b2b6d9b886413af9d056
